package protocol;

import java.util.HashMap;

import protocol.RPacket.*;
import protocol.SPacket._sPacket;
import protocol.types.DWORD;

public class ID {
    // PacketID Constants for Java
    // Generated by BNETDocs: Redux on April 8, 2013
    // BNETDocs: Redux software written by Don Cullen AKA Kyro
    // Original BNETDocs content compiled by Arta & Skywing
    // Battle.net v1 Messages Constants
    // -------------------
    public static final byte SID_NULL = 0x00;
    public static final byte SID_FIRST = 0x01;
    public static final byte SID_STOPADV = 0x02;
    public static final byte SID_SERVERLIST = 0x04;
    public static final byte SID_CLIENTID = 0x05;
    public static final byte SID_STARTVERSIONING = 0x06;
    public static final byte SID_REPORTVERSION = 0x07;
    public static final byte SID_STARTADVEX = 0x08;
    public static final byte SID_GETADVLISTEX = 0x09;
    public static final byte SID_ENTERCHAT = 0x0A;
    public static final byte SID_GETCHANNELLIST = 0x0B;
    public static final byte SID_JOINCHANNEL = 0x0C;
    public static final byte SID_CHATCOMMAND = 0x0E;
    public static final byte SID_CHATEVENT = 0x0F;
    public static final byte SID_LEAVECHAT = 0x10;
    public static final byte SID_LOCALEINFO = 0x12;
    public static final byte SID_FLOODDETECTED = 0x13;
    public static final byte SID_UDPPINGRESPONSE = 0x14;
    public static final byte SID_CHECKAD = 0x15;
    public static final byte SID_CLICKAD = 0x16;
    public static final byte SID_READMEMORY = 0x17;
    public static final byte SID_REGISTRY = 0x18;
    public static final byte SID_MESSAGEBOX = 0x19;
    public static final byte SID_STARTADVEX2 = 0x1A;
    public static final byte SID_GAMEDATAADDRESS = 0x1B;
    public static final byte SID_STARTADVEX3 = 0x1C;
    public static final byte SID_LOGONCHALLENGEEX = 0x1D;
    public static final byte SID_CLIENTID2 = 0x1E;
    public static final byte SID_LEAVEGAME = 0x1F;
    public static final byte SID_ANNOUNCEMENT = 0x20;
    public static final byte SID_DISPLAYAD = 0x21;
    public static final byte SID_NOTIFYJOIN = 0x22;
    public static final byte SID_WRITECOOKIE = 0x23;
    public static final byte SID_READCOOKIE = 0x24;
    public static final byte SID_PING = 0x25;
    public static final byte SID_READUSERDATA = 0x26;
    public static final byte SID_WRITEUSERDATA = 0x27;
    public static final byte SID_LOGONCHALLENGE = 0x28;
    public static final byte SID_LOGONRESPONSE = 0x29;
    public static final byte SID_CREATEACCOUNT = 0x2A;
    public static final byte SID_SYSTEMINFO = 0x2B;
    public static final byte SID_GAMERESULT = 0x2C;
    public static final byte SID_GETICONDATA = 0x2D;
    public static final byte SID_GETLADDERDATA = 0x2E;
    public static final byte SID_FINDLADDERUSER = 0x2F;
    public static final byte SID_CDKEY = 0x30;
    public static final byte SID_CHANGEPASSWORD = 0x31;
    public static final byte SID_CHECKDATAFILE = 0x32;
    public static final byte SID_GETFILETIME = 0x33;
    public static final byte SID_QUERYREALMS = 0x34;
    public static final byte SID_PROFILE = 0x35;
    public static final byte SID_CDKEY2 = 0x36;
    public static final byte SID_LOGONRESPONSE2 = 0x3A;
    public static final byte SID_CHECKDATAFILE2 = 0x3C;
    public static final byte SID_CREATEACCOUNT2 = 0x3D;
    public static final byte SID_LOGONREALMEX = 0x3E;
    public static final byte SID_STARTVERSIONING2 = 0x3F;
    public static final byte SID_QUERYREALMS2 = 0x40;
    public static final byte SID_QUERYADURL = 0x41;
    public static final byte SID_WARCRAFTUNKNOWN = 0x43;
    public static final byte SID_WARCRAFTGENERAL = 0x44;
    public static final byte SID_NETGAMEPORT = 0x45;
    public static final byte SID_NEWS_INFO = 0x46;
    public static final byte SID_OPTIONALWORK = 0x4A;
    public static final byte SID_EXTRAWORK = 0x4B;
    public static final byte SID_REQUIREDWORK = 0x4C;
    public static final byte SID_TOURNAMENT = 0x4E;
    public static final byte SID_AUTH_INFO = 0x50;
    public static final byte SID_AUTH_CHECK = 0x51;
    public static final byte SID_AUTH_ACCOUNTCREATE = 0x52;
    public static final byte SID_AUTH_ACCOUNTLOGON = 0x53;
    public static final byte SID_AUTH_ACCOUNTLOGONPROOF = 0x54;
    public static final byte SID_AUTH_ACCOUNTCHANGE = 0x55;
    public static final byte SID_AUTH_ACCOUNTCHANGEPROOF = 0x56;
    public static final byte SID_AUTH_ACCOUNTUPGRADE = 0x57;
    public static final byte SID_AUTH_ACCOUNTUPGRADEPROOF = 0x58;
    public static final byte SID_SETEMAIL = 0x59;
    public static final byte SID_RESETPASSWORD = 0x5A;
    public static final byte SID_CHANGEEMAIL = 0x5B;
    public static final byte SID_SWITCHPRODUCT = 0x5C;
    public static final byte SID_REPORTCRASH = 0x5D;
    public static final byte SID_WARDEN = 0x5E;
    public static final byte SID_GAMEPLAYERSEARCH = 0x60;
    public static final byte SID_FRIENDSLIST = 0x65;
    public static final byte SID_FRIENDSUPDATE = 0x66;
    public static final byte SID_FRIENDSADD = 0x67;
    public static final byte SID_FRIENDSREMOVE = 0x68;
    public static final byte SID_FRIENDSPOSITION = 0x69;
    public static final byte SID_CLANFINDCANDIDATES = 0x70;
    public static final byte SID_CLANINVITEMULTIPLE = 0x71;
    public static final byte SID_CLANCREATIONINVITATION = 0x72;
    public static final byte SID_CLANDISBAND = 0x73;
    public static final byte SID_CLANMAKECHIEFTAIN = 0x74;
    public static final byte SID_CLANINFO = 0x75;
    public static final byte SID_CLANQUITNOTIFY = 0x76;
    public static final byte SID_CLANINVITATION = 0x77;
    public static final byte SID_CLANREMOVEMEMBER = 0x78;
    public static final byte SID_CLANINVITATIONRESPONSE = 0x79;
    public static final byte SID_CLANRANKCHANGE = 0x7A;
    public static final byte SID_CLANSETMOTD = 0x7B;
    public static final byte SID_CLANMOTD = 0x7C;
    public static final byte SID_CLANMEMBERLIST = 0x7D;
    public static final byte SID_CLANMEMBERREMOVED = 0x7E;
    public static final byte SID_CLANMEMBERSTATUSCHANGE = 0x7F;
    public static final byte SID_CLANMEMBERRANKCHANGE = (byte) 0x81;
    public static final byte SID_CLANMEMBERINFORMATION = (byte) 0x82;
    // Battle.net UDP Messages Constants
    // -------------------
    public static final byte PKT_STORM = 0x00;
    public static final byte PKT_CLIENTREQ = 0x03;
    public static final byte PKT_SERVERPING = 0x05;
    public static final byte PKT_KEEPALIVE = 0x07;
    public static final byte PKT_CONNTEST = 0x08;
    public static final byte PKT_CONNTEST2 = 0x09;
    // Realm Messages Constants
    // -------------------
    public static final byte MCP_STARTUP = 0x01;
    public static final byte MCP_CHARCREATE = 0x02;
    public static final byte MCP_CREATEGAME = 0x03;
    public static final byte MCP_JOINGAME = 0x04;
    public static final byte MCP_GAMELIST = 0x05;
    public static final byte MCP_GAMEINFO = 0x06;
    public static final byte MCP_CHARLOGON = 0x07;
    public static final byte MCP_CHARDELETE = 0x0A;
    public static final byte MCP_REQUESTLADDERDATA = 0x11;
    public static final byte MCP_MOTD = 0x12;
    public static final byte MCP_CANCELGAMECREATE = 0x13;
    public static final byte MCP_CREATEQUEUE = 0x14;
    public static final byte MCP_CHARRANK = 0x16;
    public static final byte MCP_CHARLIST = 0x17;
    public static final byte MCP_CHARUPGRADE = 0x18;
    public static final byte MCP_CHARLIST2 = 0x19;
    // D2GS Messages Constants
    // -------------------
    public static final byte D2GS_WALKTOLOCATION = 0x01;
    public static final byte D2GS_WALKTOENTITY = 0x02;
    public static final byte D2GS_RUNTOLOCATION = 0x03;
    public static final byte D2GS_RUNTOENTITY = 0x04;
    public static final byte D2GS_LEFTSKILLONLOCATION = 0x05;
    public static final byte D2GS_LEFTSKILLONENTITY = 0x06;
    public static final byte D2GS_LEFTSKILLONENTITYEX = 0x07;
    public static final byte D2GS_LEFTSKILLONLOCATIONEX = 0x08;
    public static final byte D2GS_LEFTSKILLONENTITYEX2 = 0x09;
    public static final byte D2GS_LEFTSKILLONENTITYEX3 = 0x0A;
    public static final byte D2GS_RIGHTSKILLONLOCATION = 0x0C;
    public static final byte D2GS_RIGHTSKILLONENTITY = 0x0D;
    public static final byte D2GS_RIGHTSKILLONENTITYEX = 0x0E;
    public static final byte D2GS_RIGHTSKILLONLOCATIONEX = 0x0F;
    public static final byte D2GS_CHARTOOBJ = 0x10;
    public static final byte D2GS_RIGHTSKILLONENTITYEX2 = 0x10;
    public static final byte D2GS_RIGHTSKILLONENTITYEX3 = 0x11;
    public static final byte D2GS_INTERACTWITHENTITY = 0x13;
    public static final byte D2GS_OVERHEADMESSAGE = 0x14;
    public static final byte D2GS_CHATMESSAGE = 0x15;
    public static final byte D2GS_PICKUPITEM = 0x16;
    public static final byte D2GS_DROPITEM = 0x17;
    public static final byte D2GS_ITEMTOBUFFER = 0x18;
    public static final byte D2GS_SMALLGOLDPICKUP = 0x19;
    public static final byte D2GS_PICKUPBUFFERITEM = 0x19;
    public static final byte D2GS_ITEMTOBODY = 0x1A;
    public static final byte D2GS_SWAP2HANDEDITEM = 0x1B;
    public static final byte D2GS_PICKUPBODYITEM = 0x1C;
    public static final byte D2GS_SETBYTEATTR = 0x1D;
    public static final byte D2GS_SWITCHBODYITEM = 0x1D;
    public static final byte D2GS_SETWORDATTR = 0x1E;
    public static final byte D2GS_SETDWORDATTR = 0x1F;
    public static final byte D2GS_SWITCHINVENTORYITEM = 0x1F;
    public static final byte D2GS_USEITEM = 0x20;
    public static final byte D2GS_STACKITEM = 0x21;
    public static final byte D2GS_REMOVESTACKITEM = 0x22;
    public static final byte D2GS_ITEMTOBELT = 0x23;
    public static final byte D2GS_REMOVEBELTITEM = 0x24;
    public static final byte D2GS_SWITCHBELTITEM = 0x25;
    public static final byte D2GS_USEBELTITEM = 0x26;
    public static final byte D2GS_INSERTSOCKETITEM = 0x28;
    public static final byte D2GS_SCROLLTOTOME = 0x29;
    public static final byte D2GS_ITEMTOCUBE = 0x2A;
    public static final byte D2GS_UNSELECTOBJ = 0x2D;
    public static final byte D2GS_NPCINIT = 0x2F;
    public static final byte D2GS_NPCCANCEL = 0x30;
    public static final byte D2GS_NPCBUY = 0x32;
    public static final byte D2GS_NPCSELL = 0x33;
    public static final byte D2GS_NPCTRADE = 0x38;
    public static final byte D2GS_CHARACTERPHRASE = 0x3F;
    public static final byte D2GS_WAYPOINT = 0x49;
    public static final byte D2GS_TRADE = 0x4F;
    public static final byte D2GS_DROPGOLD = 0x50;
    public static final byte D2GS_WORLDOBJECT = 0x51;
    public static final byte D2GS_COMPSTARTGAME = 0x5C;
    public static final byte D2GS_PARTY = 0x5E;
    public static final byte D2GS_POTIONTOMERCENARY = 0x61;
    public static final byte D2GS_GAMELOGON = 0x68;
    public static final byte D2GS_ENTERGAMEENVIRONMENT = 0x6A;
    public static final byte D2GS_PING = 0x6D;
    public static final byte D2GS_TRADEACTION = 0x77;
    public static final byte D2GS_LOGONRESPONSE = 0x7A;
    public static final byte D2GS_UNIQUEEVENTS = (byte) 0x89;
    public static final byte D2GS_STARTLOGON = (byte) 0xAF;
    // W3GS Messages Constants
    // -------------------
    public static final byte W3GS_PING_FROM_HOST = 0x01;
    public static final byte W3GS_SLOTINFOJOIN = 0x04;
    public static final byte W3GS_REJECTJOIN = 0x05;
    public static final byte W3GS_PLAYERINFO = 0x06;
    public static final byte W3GS_PLAYERLEFT = 0x07;
    public static final byte W3GS_PLAYERLOADED = 0x08;
    public static final byte W3GS_SLOTINFO = 0x09;
    public static final byte W3GS_COUNTDOWN_START = 0x0A;
    public static final byte W3GS_COUNTDOWN_END = 0x0B;
    public static final byte W3GS_INCOMING_ACTION = 0x0C;
    public static final byte W3GS_CHAT_FROM_HOST = 0x0F;
    public static final byte W3GS_LEAVERS = 0x1B;
    public static final byte W3GS_REQJOIN = 0x1E;
    public static final byte W3GS_LEAVEREQ = 0x21;
    public static final byte W3GS_GAMELOADED_SELF = 0x23;
    public static final byte W3GS_OUTGOING_ACTION = 0x26;
    public static final byte W3GS_OUTGOING_KEEPALIVE = 0x27;
    public static final byte W3GS_CHAT_TO_HOST = 0x28;
    public static final byte W3GS_SEARCHGAME = 0x2F;
    public static final byte W3GS_GAMEINFO = 0x30;
    public static final byte W3GS_CREATEGAME = 0x31;
    public static final byte W3GS_REFRESHGAME = 0x32;
    public static final byte W3GS_DECREATEGAME = 0x33;
    public static final byte W3GS_PING_FROM_OTHERS = 0x35;
    public static final byte W3GS_PONG_TO_OTHERS = 0x36;
    public static final byte W3GS_CLIENTINFO = 0x37;
    public static final byte W3GS_MAPCHECK = 0x3D;
    public static final byte W3GS_STARTDOWNLOAD = 0x3F;
    public static final byte W3GS_MAPSIZE = 0x42;
    public static final byte W3GS_MAPPART = 0x43;
    public static final byte W3GS_MAPPARTOK = 0x44;
    public static final byte W3GS_MAPPARTNOTOK = 0x45;
    public static final byte W3GS_PONG_TO_HOST = 0x46;
    public static final byte W3GS_INCOMING_ACTION2 = 0x48;
    // BotNet Messages Constants
    // -------------------
    public static final byte PACKET_IDLE = 0x00;
    public static final byte PACKET_LOGON = 0x01;
    public static final byte PACKET_STATSUPDATE = 0x02;
    public static final byte PACKET_DATABASE = 0x03;
    public static final byte PACKET_MESSAGE = 0x04;
    public static final byte PACKET_CYCLE = 0x05;
    public static final byte PACKET_USERINFO = 0x06;
    public static final byte PACKET_USERLOGGINGOFF = 0x07;
    public static final byte PACKET_BROADCASTMESSAGE = 0x07;
    public static final byte PACKET_COMMAND = 0x08;
    public static final byte PACKET_CHANGEDBPASSWORD = 0x09;
    public static final byte PACKET_BOTNETVERSION = 0x0A;
    public static final byte PACKET_BOTNETCHAT = 0x0B;
    public static final byte PACKET_ACCOUNT = 0x0D;
    public static final byte PACKET_CHATDROPOPTIONS = 0x10;
    // BNLS Messages Constants
    // -------------------
    public static final byte BNLS_NULL = 0x00;
    public static final byte BNLS_CDKEY = 0x01;
    public static final byte BNLS_LOGONCHALLENGE = 0x02;
    public static final byte BNLS_LOGONPROOF = 0x03;
    public static final byte BNLS_CREATEACCOUNT = 0x04;
    public static final byte BNLS_CHANGECHALLENGE = 0x05;
    public static final byte BNLS_CHANGEPROOF = 0x06;
    public static final byte BNLS_UPGRADECHALLENGE = 0x07;
    public static final byte BNLS_UPGRADEPROOF = 0x08;
    public static final byte BNLS_VERSIONCHECK = 0x09;
    public static final byte BNLS_CONFIRMLOGON = 0x0A;
    public static final byte BNLS_HASHDATA = 0x0B;
    public static final byte BNLS_CDKEY_EX = 0x0C;
    public static final byte BNLS_CHOOSENLSREVISION = 0x0D;
    public static final byte BNLS_AUTHORIZE = 0x0E;
    public static final byte BNLS_AUTHORIZEPROOF = 0x0F;
    public static final byte BNLS_REQUESTVERSIONBYTE = 0x10;
    public static final byte BNLS_VERIFYSERVER = 0x11;
    public static final byte BNLS_RESERVESERVERSLOTS = 0x12;
    public static final byte BNLS_SERVERLOGONCHALLENGE = 0x13;
    public static final byte BNLS_SERVERLOGONPROOF = 0x14;
    public static final byte BNLS_VERSIONCHECKEX = 0x18;
    public static final byte BNLS_VERSIONCHECKEX2 = 0x1A;
    public static final byte BNLS_WARDEN = 0x7D;
    public static final byte BNLS_IPBAN = (byte) 0xFF;
    // SCGP Messages Constants
    // -------------------
    public static final byte SCGP_GAMECHATPUBLIC = 0x00;
    public static final byte SCGP_GAMECHATPRIVATE = 0x01;
    public static final byte SCGP_GAMECHATNULL = 0x02;
    public static final byte SCGP_NOP = 0x05;
    public static final byte SCGP_GAMESTART = 0x3C;
    public static final byte SCGP_MAPPERCENT = 0x3D;
    public static final byte SCGP_SLOTUPDATE = 0x3E;
    public static final byte SCGP_HUMAN = 0x3F;
    public static final byte SCGP_UNKNOWNRESPONSE = 0x40;
    public static final byte SCGP_CHANGERACE = 0x41;
    public static final byte SCGP_CHANGETEAM = 0x42;
    public static final byte SCGP_CHANGETEAMUMS = 0x43;
    public static final byte SCGP_CHANGESLOTSTATE = 0x44;
    public static final byte SCGP_SLOTSWITCH = 0x45;
    public static final byte SCGP_SEED = 0x48;
    public static final byte SCGP_PLAYERJOIN = 0x49;
    public static final byte SCGP_ROOMDATA = 0x4A;
    public static final byte SCGP_FORCENAMES = 0x4B;
    public static final byte SCGP_LOBBYCHAT = 0x4C;
    public static final byte SCGP_REJECT = 0x4E;
    public static final byte SCGP_MAP = 0x4F;
    public static final byte SCGP_UNKNOWNREQUEST = 0x50;
    // Event IDs:
    // -------------------
    public static final byte EID_SHOWUSER = 0x01;
    public static final byte EID_JOIN = 0x02;
    public static final byte EID_LEAVE = 0x03;
    public static final byte EID_WHISPER = 0x04;
    public static final byte EID_TALK = 0x05;
    public static final byte EID_BROADCAST = 0x06;
    public static final byte EID_CHANNEL = 0x07;
    public static final byte EID_USERFLAGS = 0x09;
    public static final byte EID_WHISPERSENT = 0x0A;
    public static final byte EID_CHANNELFULL = 0x0D;
    public static final byte EID_CHANNELDOESNOTEXIST = 0x0E;
    public static final byte EID_CHANNELRESTRICTED = 0x0F;
    public static final byte EID_INFO = 0x12;
    public static final byte EID_ERROR = 0x13;
    public static final byte EID_IGNORE = 0x15;
    public static final byte EID_ACCEPT = 0x16;
    public static final byte EID_EMOTE = 0x17;

    public static final DWORD FLAG_Blizzard_Representative = new DWORD(0x00000001);
    public static final DWORD FLAG_Channel_Operator = new DWORD(0x00000002);
    public static final DWORD FLAG_Speaker = new DWORD(0x00000004);
    public static final DWORD FLAG_Battlenet_Administrator = new DWORD(0x00000008);

    // Bitwise-values and meanings for Status:
    public static final byte Status_Mutual = 0x01;
    public static final byte Status_DND = 0x02;
    public static final byte Status_Away = 0x04;

    // Value and meanings for Location:
    public static final byte Location_Offline = 0x00;
    public static final byte Location_Not_in_chat = 0x01;
    public static final byte Location_In_chat = 0x02;
    public static final byte Location_In_public_game = 0x03;
    public static final byte Location_In_private_game_Not_on_your_friends_list = 0x04;
    public static final byte Location_In_private_game_Is_on_your_friends_list = 0x05;

    // Version bytes:
    //public static final byte VersionByte_Telnet = 0x01;
    //public static final byte VersionByte_Starcraft = (byte) 0xD3;
    //public static final byte VersionByte_Diablo_I = 0x2A;
    //public static final byte VersionByte_Diablo_II = 0x0D;
    //public static final byte VersionByte_Warcraft_II = 0x4F;
    //public static final byte VersionByte_Warcraft_III = 0x1C;

    // Product ID
    public static final DWORD ProductID_Telnet = new DWORD(_sPacket.reverse("CHAT".getBytes()));
    public static final DWORD ProductID_Starcraft = new DWORD(_sPacket.reverse("STAR".getBytes()));
    public static final DWORD ProductID_Diablo_I = new DWORD(_sPacket.reverse("DRTL".getBytes()));
    public static final DWORD ProductID_Diablo_II = new DWORD(_sPacket.reverse("D2DV".getBytes()));
    public static final DWORD ProductID_Warcraft_II = new DWORD(_sPacket.reverse("W2BN".getBytes()));
    public static final DWORD ProductID_Warcraft_III = new DWORD(_sPacket.reverse("W3XP".getBytes()));

    // Channel join flags
    public static final byte ChannelJoin_NoCreate = 0x00;
    public static final byte ChannelJoin_First = 0x01;
    public static final byte ChannelJoin_Forced = 0x02;
    public static final byte ChannelJoin_D2_first = 0x05;

    // TODO: implement those:

    // 0x00000001: Blizzard Representative
    // 0x00000002: Channel Operator
    // 0x00000004: Speaker
    // 0x00000008: Battle.net Administrator
    // 0x00000010: No UDP Support
    // 0x00000020: Squelched
    // 0x00000040: Special Guest
    // 0x00000080: This flag has not been seen, however, it is logical to assume
    // that it was once used since it is in the middle of a sequence.
    // 0x00000100: Beep Enabled (Defunct)
    // 0x00000200: PGL Player (Defunct)
    // 0x00000400: PGL Official (Defunct)
    // 0x00000800: KBK Player (Defunct)
    // 0x00001000: WCG Official
    // 0x00002000: KBK Singles (Defunct)
    // 0x00002000: KBK Player (Defunct)
    // 0x00010000: KBK Beginner (Defunct)
    // 0x00020000: White KBK (1 bar) (Defunct)
    // 0x00100000: GF Official
    // 0x00200000: GF Player
    // 0x02000000: PGL Player

    public static HashMap<Byte, Class<? extends _rPacket>> rPackets = new HashMap<Byte, Class<? extends _rPacket>>();

    static {
        rPackets.put(SID_NULL, SID_NULL_r.class);
        rPackets.put(SID_FIRST, SID_FIRST_r.class);
        rPackets.put(SID_STOPADV, SID_STOPADV_r.class);
        rPackets.put(SID_SERVERLIST, SID_SERVERLIST_r.class);
        rPackets.put(SID_CLIENTID, SID_CLIENTID_r.class);
        rPackets.put(SID_STARTVERSIONING, SID_STARTVERSIONING_r.class);
        rPackets.put(SID_REPORTVERSION, SID_REPORTVERSION_r.class);
        rPackets.put(SID_STARTADVEX, SID_STARTADVEX_r.class);
        rPackets.put(SID_GETADVLISTEX, SID_GETADVLISTEX_r.class);
        rPackets.put(SID_ENTERCHAT, SID_ENTERCHAT_r.class);
        rPackets.put(SID_GETCHANNELLIST, SID_GETCHANNELLIST_r.class);
        rPackets.put(SID_JOINCHANNEL, SID_JOINCHANNEL_r.class);
        rPackets.put(SID_CHATCOMMAND, SID_CHATCOMMAND_r.class);
        rPackets.put(SID_CHATEVENT, SID_CHATEVENT_r.class);
        rPackets.put(SID_LEAVECHAT, SID_LEAVECHAT_r.class);
        rPackets.put(SID_LOCALEINFO, SID_LOCALEINFO_r.class);
        rPackets.put(SID_FLOODDETECTED, SID_FLOODDETECTED_r.class);
        rPackets.put(SID_UDPPINGRESPONSE, SID_UDPPINGRESPONSE_r.class);
        rPackets.put(SID_CHECKAD, SID_CHECKAD_r.class);
        rPackets.put(SID_CLICKAD, SID_CLICKAD_r.class);
        rPackets.put(SID_READMEMORY, SID_READMEMORY_r.class);
        rPackets.put(SID_REGISTRY, SID_REGISTRY_r.class);
        rPackets.put(SID_MESSAGEBOX, SID_MESSAGEBOX_r.class);
        rPackets.put(SID_STARTADVEX2, SID_STARTADVEX2_r.class);
        rPackets.put(SID_GAMEDATAADDRESS, SID_GAMEDATAADDRESS_r.class);
        rPackets.put(SID_STARTADVEX3, SID_STARTADVEX3_r.class);
        rPackets.put(SID_LOGONCHALLENGEEX, SID_LOGONCHALLENGEEX_r.class);
        rPackets.put(SID_CLIENTID2, SID_CLIENTID2_r.class);
        rPackets.put(SID_LEAVEGAME, SID_LEAVEGAME_r.class);
        rPackets.put(SID_ANNOUNCEMENT, SID_ANNOUNCEMENT_r.class);
        rPackets.put(SID_DISPLAYAD, SID_DISPLAYAD_r.class);
        rPackets.put(SID_NOTIFYJOIN, SID_NOTIFYJOIN_r.class);
        rPackets.put(SID_WRITECOOKIE, SID_WRITECOOKIE_r.class);
        rPackets.put(SID_READCOOKIE, SID_READCOOKIE_r.class);
        rPackets.put(SID_PING, SID_PING_r.class);
        rPackets.put(SID_READUSERDATA, SID_READUSERDATA_r.class);
        rPackets.put(SID_WRITEUSERDATA, SID_WRITEUSERDATA_r.class);
        rPackets.put(SID_LOGONCHALLENGE, SID_LOGONCHALLENGE_r.class);
        rPackets.put(SID_LOGONRESPONSE, SID_LOGONRESPONSE_r.class);
        rPackets.put(SID_CREATEACCOUNT, SID_CREATEACCOUNT_r.class);
        rPackets.put(SID_SYSTEMINFO, SID_SYSTEMINFO_r.class);
        rPackets.put(SID_GAMERESULT, SID_GAMERESULT_r.class);
        rPackets.put(SID_GETICONDATA, SID_GETICONDATA_r.class);
        rPackets.put(SID_GETLADDERDATA, SID_GETLADDERDATA_r.class);
        rPackets.put(SID_FINDLADDERUSER, SID_FINDLADDERUSER_r.class);
        rPackets.put(SID_CDKEY, SID_CDKEY_r.class);
        rPackets.put(SID_CHANGEPASSWORD, SID_CHANGEPASSWORD_r.class);
        rPackets.put(SID_CHECKDATAFILE, SID_CHECKDATAFILE_r.class);
        rPackets.put(SID_GETFILETIME, SID_GETFILETIME_r.class);
        rPackets.put(SID_QUERYREALMS, SID_QUERYREALMS_r.class);
        rPackets.put(SID_PROFILE, SID_PROFILE_r.class);
        rPackets.put(SID_CDKEY2, SID_CDKEY2_r.class);
        rPackets.put(SID_LOGONRESPONSE2, SID_LOGONRESPONSE2_r.class);
        rPackets.put(SID_CHECKDATAFILE2, SID_CHECKDATAFILE2_r.class);
        rPackets.put(SID_CREATEACCOUNT2, SID_CREATEACCOUNT2_r.class);
        rPackets.put(SID_LOGONREALMEX, SID_LOGONREALMEX_r.class);
        rPackets.put(SID_STARTVERSIONING2, SID_STARTVERSIONING2_r.class);
        rPackets.put(SID_QUERYREALMS2, SID_QUERYREALMS2_r.class);
        rPackets.put(SID_QUERYADURL, SID_QUERYADURL_r.class);
        rPackets.put(SID_WARCRAFTUNKNOWN, SID_WARCRAFTUNKNOWN_r.class);
        rPackets.put(SID_WARCRAFTGENERAL, SID_WARCRAFTGENERAL_r.class);
        rPackets.put(SID_NETGAMEPORT, SID_NETGAMEPORT_r.class);
        rPackets.put(SID_NEWS_INFO, SID_NEWS_INFO_r.class);
        rPackets.put(SID_OPTIONALWORK, SID_OPTIONALWORK_r.class);
        rPackets.put(SID_EXTRAWORK, SID_EXTRAWORK_r.class);
        rPackets.put(SID_REQUIREDWORK, SID_REQUIREDWORK_r.class);
        rPackets.put(SID_TOURNAMENT, SID_TOURNAMENT_r.class);
        rPackets.put(SID_AUTH_INFO, SID_AUTH_INFO_r.class);
        rPackets.put(SID_AUTH_CHECK, SID_AUTH_CHECK_r.class);
        rPackets.put(SID_AUTH_ACCOUNTCREATE, SID_AUTH_ACCOUNTCREATE_r.class);
        rPackets.put(SID_AUTH_ACCOUNTLOGON, SID_AUTH_ACCOUNTLOGON_r.class);
        rPackets.put(SID_AUTH_ACCOUNTLOGONPROOF, SID_AUTH_ACCOUNTLOGONPROOF_r.class);
        rPackets.put(SID_AUTH_ACCOUNTCHANGE, SID_AUTH_ACCOUNTCHANGE_r.class);
        rPackets.put(SID_AUTH_ACCOUNTCHANGEPROOF, SID_AUTH_ACCOUNTCHANGEPROOF_r.class);
        rPackets.put(SID_AUTH_ACCOUNTUPGRADE, SID_AUTH_ACCOUNTUPGRADE_r.class);
        rPackets.put(SID_AUTH_ACCOUNTUPGRADEPROOF, SID_AUTH_ACCOUNTUPGRADEPROOF_r.class);
        rPackets.put(SID_SETEMAIL, SID_SETEMAIL_r.class);
        rPackets.put(SID_RESETPASSWORD, SID_RESETPASSWORD_r.class);
        rPackets.put(SID_CHANGEEMAIL, SID_CHANGEEMAIL_r.class);
        rPackets.put(SID_SWITCHPRODUCT, SID_SWITCHPRODUCT_r.class);
        rPackets.put(SID_REPORTCRASH, SID_REPORTCRASH_r.class);
        rPackets.put(SID_WARDEN, SID_WARDEN_r.class);
        rPackets.put(SID_GAMEPLAYERSEARCH, SID_GAMEPLAYERSEARCH_r.class);
        rPackets.put(SID_FRIENDSLIST, SID_FRIENDSLIST_r.class);
        rPackets.put(SID_FRIENDSUPDATE, SID_FRIENDSUPDATE_r.class);
        rPackets.put(SID_FRIENDSADD, SID_FRIENDSADD_r.class);
        rPackets.put(SID_FRIENDSREMOVE, SID_FRIENDSREMOVE_r.class);
        rPackets.put(SID_FRIENDSPOSITION, SID_FRIENDSPOSITION_r.class);
        rPackets.put(SID_CLANFINDCANDIDATES, SID_CLANFINDCANDIDATES_r.class);
        rPackets.put(SID_CLANINVITEMULTIPLE, SID_CLANINVITEMULTIPLE_r.class);
        rPackets.put(SID_CLANCREATIONINVITATION, SID_CLANCREATIONINVITATION_r.class);
        rPackets.put(SID_CLANDISBAND, SID_CLANDISBAND_r.class);
        rPackets.put(SID_CLANMAKECHIEFTAIN, SID_CLANMAKECHIEFTAIN_r.class);
        rPackets.put(SID_CLANINFO, SID_CLANINFO_r.class);
        rPackets.put(SID_CLANQUITNOTIFY, SID_CLANQUITNOTIFY_r.class);
        rPackets.put(SID_CLANINVITATION, SID_CLANINVITATION_r.class);
        rPackets.put(SID_CLANREMOVEMEMBER, SID_CLANREMOVEMEMBER_r.class);
        rPackets.put(SID_CLANINVITATIONRESPONSE, SID_CLANINVITATIONRESPONSE_r.class);
        rPackets.put(SID_CLANRANKCHANGE, SID_CLANRANKCHANGE_r.class);
        rPackets.put(SID_CLANSETMOTD, SID_CLANSETMOTD_r.class);
        rPackets.put(SID_CLANMOTD, SID_CLANMOTD_r.class);
        rPackets.put(SID_CLANMEMBERLIST, SID_CLANMEMBERLIST_r.class);
        rPackets.put(SID_CLANMEMBERREMOVED, SID_CLANMEMBERREMOVED_r.class);
        rPackets.put(SID_CLANMEMBERSTATUSCHANGE, SID_CLANMEMBERSTATUSCHANGE_r.class);
        rPackets.put(SID_CLANMEMBERRANKCHANGE, SID_CLANMEMBERRANKCHANGE_r.class);
        rPackets.put(SID_CLANMEMBERINFORMATION, SID_CLANMEMBERINFORMATION_r.class);
    }
}
